[build]
  publish = "newsite"
  functions = "netlify/functions"

[functions]
  included_files = ["private-files/**"]

[functions.secure-download]
  timeout = 30
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/secure-download"
  to = "/.netlify/functions/secure-download"
  status = 200


