[build]
  publish = "newsite"
  functions = "netlify/functions"

[functions]
  included_files = ["private-files/**"]

[[redirects]]
  from = "/api/secure-download"
  to = "/.netlify/functions/secure-download"
  status = 200


